// AUTO-GENERATED: 300+ special backgrounds for global, national, and event days (no Pride Day)
// Each entry uses the best available emoji/icon for the event
// This file is intended to be imported and merged with your main specialBackgrounds.ts

import { SpecialBackground } from './specialBackgrounds';

export const generatedSpecialBackgrounds: SpecialBackground[] = [
  // Existing entries...
  {
    id: 'new-year',
    name: "New Year's Day",
    date: '01-01',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🎆',
    description: "Happy New Year!",
  },
  {
    id: 'valentines',
    name: "Valentine's Day",
    date: '02-14',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #ff6a88 0%, #ff99ac 100%)',
    icon: '💘',
    description: "Spread the love!",
  },
  {
    id: 'april-fools',
    name: "April Fools' Day",
    date: '04-01',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🤡',
    description: "Don't get tricked!",
  },
  {
    id: 'earth-day',
    name: "Earth Day",
    date: '04-22',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)',
    icon: '🌍',
    description: "Protect our planet!",
  },
  {
    id: 'halloween',
    name: "Halloween",
    date: '10-31',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #232526 0%, #ff512f 100%)',
    icon: '🎃',
    description: "Spooky fun!",
  },
  {
    id: 'thanksgiving-us',
    name: "Thanksgiving (US)",
    date: { rule: 'fourth Thursday in November' },
    countries: ['US'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🦃',
    description: "Give thanks!",
  },
  // More global and national holidays:
  {
    id: 'christmas',
    name: "Christmas Day",
    date: '12-25',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    icon: '🎄',
    description: "Merry Christmas!",
  },
  {
    id: 'easter',
    name: "Easter Sunday",
    date: { rule: 'easter' },
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #fcb69f 0%, #ffecd2 100%)',
    icon: '🐣',
    description: "Happy Easter!",
  },
  {
    id: 'eid-al-fitr',
    name: "Eid al-Fitr",
    date: { rule: 'islamic calendar' },
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🌙',
    description: "Eid Mubarak!",
  },
  {
    id: 'diwali',
    name: "Diwali",
    date: { rule: 'hindu calendar' },
    countries: ['IN', 'NP', 'SG', 'MY', 'FJ', 'TT'],
    background: 'linear-gradient(135deg, #fc466b 0%, #3f5efb 100%)',
    icon: '🪔',
    description: "Happy Diwali!",
  },
  {
    id: 'chinese-new-year',
    name: "Chinese New Year",
    date: { rule: 'chinese calendar' },
    countries: ['CN', 'SG', 'MY', 'TW', 'HK'],
    background: 'linear-gradient(135deg, #ff512f 0%, #dd2476 100%)',
    icon: '🧧',
    description: "Happy Lunar New Year!",
  },
  {
    id: 'independence-us',
    name: "US Independence Day",
    date: '07-04',
    countries: ['US'],
    background: 'linear-gradient(135deg, #3a6186 0%, #89253e 100%)',
    icon: '🇺🇸',
    description: "Happy 4th of July!",
  },
  {
    id: 'independence-nigeria',
    name: "Nigeria Independence Day",
    date: '10-01',
    countries: ['NG'],
    background: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    icon: '🇳🇬',
    description: "Happy Independence Day, Nigeria!",
  },
  {
    id: 'independence-india',
    name: "India Independence Day",
    date: '08-15',
    countries: ['IN'],
    background: 'linear-gradient(135deg, #ff9933 0%, #ffffff 50%, #138808 100%)',
    icon: '🇮🇳',
    description: "Happy Independence Day, India!",
  },
  {
    id: 'mandela-day',
    name: "Mandela Day",
    date: '07-18',
    countries: ['ZA'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🕊️',
    description: "Nelson Mandela International Day",
  },
  {
    id: 'womens-day',
    name: "International Women’s Day",
    date: '03-08',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f953c6 0%, #b91d73 100%)',
    icon: '♀️',
    description: "Celebrating women everywhere!",
  },
  {
    id: 'childrens-day',
    name: "International Children’s Day",
    date: '06-01',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)',
    icon: '🧒',
    description: "Happy Children's Day!",
  },
  {
    id: 'autism-awareness',
    name: "World Autism Awareness Day",
    date: '04-02',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #2980b9 0%, #6dd5fa 100%)',
    icon: '🧩',
    description: "Support Autism Awareness!",
  },
  {
    id: 'aids-day',
    name: "World AIDS Day",
    date: '12-01',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #ff512f 0%, #dd2476 100%)',
    icon: '🎗️',
    description: "Support AIDS Awareness!",
  },

  // ...existing entries...
  {
    id: 'independence-south-africa',
    name: "South Africa Freedom Day",
    date: '04-27',
    countries: ['ZA'],
    background: 'linear-gradient(135deg, #007749 0%, #ffb81c 50%, #de3831 100%)',
    icon: '🇿🇦',
    description: "Happy Freedom Day, South Africa!",
  },
  {
    id: 'independence-ghana',
    name: "Ghana Independence Day",
    date: '03-06',
    countries: ['GH'],
    background: 'linear-gradient(135deg, #fcd116 0%, #e8112d 50%, #008751 100%)',
    icon: '🇬🇭',
    description: "Happy Independence Day, Ghana!",
  },
  {
    id: 'independence-kenya',
    name: "Kenya Independence Day",
    date: '12-12',
    countries: ['KE'],
    background: 'linear-gradient(135deg, #006600 0%, #ff0000 50%, #000000 100%)',
    icon: '🇰🇪',
    description: "Happy Jamhuri Day, Kenya!",
  },
  {
    id: 'independence-brazil',
    name: "Brazil Independence Day",
    date: '09-07',
    countries: ['BR'],
    background: 'linear-gradient(135deg, #3e4095 0%, #ffcc29 50%, #009739 100%)',
    icon: '🇧🇷',
    description: "Happy Independence Day, Brazil!",
  },
  {
    id: 'independence-france',
    name: "Bastille Day (France)",
    date: '07-14',
    countries: ['FR'],
    background: 'linear-gradient(135deg, #0055a4 0%, #ffffff 50%, #ef4135 100%)',
    icon: '🇫🇷',
    description: "Joyeux 14 Juillet!",
  },
  {
    id: 'independence-canada',
    name: "Canada Day",
    date: '07-01',
    countries: ['CA'],
    background: 'linear-gradient(135deg, #ff0000 0%, #ffffff 100%)',
    icon: '🇨🇦',
    description: "Happy Canada Day!",
  },
  {
    id: 'independence-mexico',
    name: "Mexico Independence Day",
    date: '09-16',
    countries: ['MX'],
    background: 'linear-gradient(135deg, #006341 0%, #ffffff 50%, #ce1126 100%)',
    icon: '🇲🇽',
    description: "¡Viva México!",
  },
  {
    id: 'independence-japan',
    name: "Japan National Foundation Day",
    date: '02-11',
    countries: ['JP'],
    background: 'linear-gradient(135deg, #ffffff 0%, #bc002d 100%)',
    icon: '🇯🇵',
    description: "Happy National Foundation Day, Japan!",
  },
  {
    id: 'independence-egypt',
    name: "Egypt Revolution Day",
    date: '07-23',
    countries: ['EG'],
    background: 'linear-gradient(135deg, #ce1126 0%, #ffffff 50%, #000000 100%)',
    icon: '🇪🇬',
    description: "Happy Revolution Day, Egypt!",
  },
  {
    id: 'independence-saudi',
    name: "Saudi National Day",
    date: '09-23',
    countries: ['SA'],
    background: 'linear-gradient(135deg, #006c35 0%, #ffffff 100%)',
    icon: '🇸🇦',
    description: "Happy National Day, Saudi Arabia!",
  },
  {
    id: 'independence-uk',
    name: "United Kingdom National Day",
    date: '06-02',
    countries: ['GB'],
    background: 'linear-gradient(135deg, #00247d 0%, #ffffff 50%, #cf142b 100%)',
    icon: '🇬🇧',
    description: "Happy National Day, UK!",
  },
  {
    id: 'independence-australia',
    name: "Australia Day",
    date: '01-26',
    countries: ['AU'],
    background: 'linear-gradient(135deg, #012169 0%, #ffffff 50%, #e4002b 100%)',
    icon: '🇦🇺',
    description: "Happy Australia Day!",
  },
  {
    id: 'independence-china',
    name: "China National Day",
    date: '10-01',
    countries: ['CN'],
    background: 'linear-gradient(135deg, #de2910 0%, #ffde00 100%)',
    icon: '🇨🇳',
    description: "Happy National Day, China!",
  },
  {
    id: 'independence-russia',
    name: "Russia Day",
    date: '06-12',
    countries: ['RU'],
    background: 'linear-gradient(135deg, #ffffff 0%, #0033a0 50%, #d52b1e 100%)',
    icon: '🇷🇺',
    description: "Happy Russia Day!",
  },
  {
    id: 'independence-turkey',
    name: "Republic Day (Turkey)",
    date: '10-29',
    countries: ['TR'],
    background: 'linear-gradient(135deg, #e30a17 0%, #ffffff 100%)',
    icon: '🇹🇷',
    description: "Happy Republic Day, Turkey!",
  },
  {
    id: 'independence-uae',
    name: "UAE National Day",
    date: '12-02',
    countries: ['AE'],
    background: 'linear-gradient(135deg, #00732f 0%, #ffffff 33%, #ff0000 66%, #000000 100%)',
    icon: '🇦🇪',
    description: "Happy National Day, UAE!",
  },
  {
    id: 'independence-pakistan',
    name: "Pakistan Independence Day",
    date: '08-14',
    countries: ['PK'],
    background: 'linear-gradient(135deg, #01411c 0%, #ffffff 100%)',
    icon: '🇵🇰',
    description: "Happy Independence Day, Pakistan!",
  },
  {
    id: 'independence-argentina',
    name: "Argentina Independence Day",
    date: '07-09',
    countries: ['AR'],
    background: 'linear-gradient(135deg, #74acdf 0%, #ffffff 50%, #74acdf 100%)',
    icon: '🇦🇷',
    description: "Happy Independence Day, Argentina!",
  },
  {
    id: 'independence-south-korea',
    name: "South Korea Liberation Day",
    date: '08-15',
    countries: ['KR'],
    background: 'linear-gradient(135deg, #ffffff 0%, #003478 50%, #c60c30 100%)',
    icon: '🇰🇷',
    description: "Happy Liberation Day, South Korea!",
  },
  {
    id: 'independence-italy',
    name: "Italy Republic Day",
    date: '06-02',
    countries: ['IT'],
    background: 'linear-gradient(135deg, #008c45 0%, #ffffff 50%, #cd212a 100%)',
    icon: '🇮🇹',
    description: "Happy Republic Day, Italy!",
  },
  {
    id: 'independence-germany',
    name: "German Unity Day",
    date: '10-03',
    countries: ['DE'],
    background: 'linear-gradient(135deg, #000000 0%, #dd0000 50%, #ffce00 100%)',
    icon: '🇩🇪',
    description: "Happy Unity Day, Germany!",
  },
  {
    id: 'independence-egypt',
    name: "Egypt Revolution Day",
    date: '07-23',
    countries: ['EG'],
    background: 'linear-gradient(135deg, #ce1126 0%, #ffffff 50%, #000000 100%)',
    icon: '🇪🇬',
    description: "Happy Revolution Day, Egypt!",
  },



  // --- WEST AFRICA ---
{
  id: 'independence-ghana',
  name: "Ghana Independence Day",
  date: '03-06',
  countries: ['GH'],
  background: 'linear-gradient(135deg, #fcd116 0%, #e8112d 50%, #008751 100%)',
  icon: '🇬🇭',
  description: "Happy Independence Day, Ghana!",
},
{
  id: 'independence-nigeria',
  name: "Nigeria Independence Day",
  date: '10-01',
  countries: ['NG'],
  background: 'linear-gradient(135deg, #008753 0%, #ffffff 50%, #008753 100%)',
  icon: '🇳🇬',
  description: "Happy Independence Day, Nigeria!",
},
{
  id: 'independence-senegal',
  name: "Senegal Independence Day",
  date: '04-04',
  countries: ['SN'],
  background: 'linear-gradient(135deg, #00853f 0%, #ffd100 50%, #e31b23 100%)',
  icon: '🇸🇳',
  description: "Happy Independence Day, Senegal!",
},
{
  id: 'independence-ivory-coast',
  name: "Ivory Coast Independence Day",
  date: '08-07',
  countries: ['CI'],
  background: 'linear-gradient(135deg, #f77f00 0%, #ffffff 50%, #009e60 100%)',
  icon: '🇨🇮',
  description: "Happy Independence Day, Côte d'Ivoire!",
},
{
  id: 'independence-burkina-faso',
  name: "Burkina Faso Independence Day",
  date: '08-05',
  countries: ['BF'],
  background: 'linear-gradient(135deg, #ef2b2d 0%, #009e49 100%)',
  icon: '🇧🇫',
  description: "Happy Independence Day, Burkina Faso!",
},
{
  id: 'independence-mali',
  name: "Mali Independence Day",
  date: '09-22',
  countries: ['ML'],
  background: 'linear-gradient(135deg, #14b53a 0%, #fcd116 50%, #ce1126 100%)',
  icon: '🇲🇱',
  description: "Happy Independence Day, Mali!",
},
{
  id: 'independence-guinea',
  name: "Guinea Independence Day",
  date: '10-02',
  countries: ['GN'],
  background: 'linear-gradient(135deg, #ce1126 0%, #fcd116 50%, #009460 100%)',
  icon: '🇬🇳',
  description: "Happy Independence Day, Guinea!",
},
{
  id: 'independence-benin',
  name: "Benin Independence Day",
  date: '08-01',
  countries: ['BJ'],
  background: 'linear-gradient(135deg, #008751 0%, #ffd100 50%, #e31b23 100%)',
  icon: '🇧🇯',
  description: "Happy Independence Day, Benin!",
},
{
  id: 'independence-togo',
  name: "Togo Independence Day",
  date: '04-27',
  countries: ['TG'],
  background: 'linear-gradient(135deg, #006a4e 0%, #ffce00 50%, #d21034 100%)',
  icon: '🇹🇬',
  description: "Happy Independence Day, Togo!",
},
{
  id: 'independence-liberia',
  name: "Liberia Independence Day",
  date: '07-26',
  countries: ['LR'],
  background: 'linear-gradient(135deg, #c60c30 0%, #ffffff 50%, #003893 100%)',
  icon: '🇱🇷',
  description: "Happy Independence Day, Liberia!",
},
{
  id: 'independence-sierra-leone',
  name: "Sierra Leone Independence Day",
  date: '04-27',
  countries: ['SL'],
  background: 'linear-gradient(135deg, #1eb53a 0%, #ffffff 50%, #0072c6 100%)',
  icon: '🇸🇱',
  description: "Happy Independence Day, Sierra Leone!",
},
{
  id: 'independence-gambia',
  name: "Gambia Independence Day",
  date: '02-18',
  countries: ['GM'],
  background: 'linear-gradient(135deg, #3a7728 0%, #ffffff 33%, #ce1126 66%, #0c1c8c 100%)',
  icon: '🇬🇲',
  description: "Happy Independence Day, Gambia!",
},

// --- SOUTHERN AFRICA ---
{
  id: 'independence-south-africa',
  name: "South Africa Freedom Day",
  date: '04-27',
  countries: ['ZA'],
  background: 'linear-gradient(135deg, #007749 0%, #ffb81c 50%, #de3831 100%)',
  icon: '🇿🇦',
  description: "Happy Freedom Day, South Africa!",
},
{
  id: 'independence-botswana',
  name: "Botswana Independence Day",
  date: '09-30',
  countries: ['BW'],
  background: 'linear-gradient(135deg, #00a2dd 0%, #ffffff 50%, #000000 100%)',
  icon: '🇧🇼',
  description: "Happy Independence Day, Botswana!",
},
{
  id: 'independence-namibia',
  name: "Namibia Independence Day",
  date: '03-21',
  countries: ['NA'],
  background: 'linear-gradient(135deg, #003580 0%, #ffffff 33%, #d21034 66%, #009543 100%)',
  icon: '🇳🇦',
  description: "Happy Independence Day, Namibia!",
},
{
  id: 'independence-zimbabwe',
  name: "Zimbabwe Independence Day",
  date: '04-18',
  countries: ['ZW'],
  background: 'linear-gradient(135deg, #006400 0%, #ffd700 50%, #ff0000 100%)',
  icon: '🇿🇼',
  description: "Happy Independence Day, Zimbabwe!",
},
{
  id: 'independence-mozambique',
  name: "Mozambique Independence Day",
  date: '06-25',
  countries: ['MZ'],
  background: 'linear-gradient(135deg, #ff0000 0%, #000000 33%, #ffcb00 66%, #007168 100%)',
  icon: '🇲🇿',
  description: "Happy Independence Day, Mozambique!",
},
{
  id: 'independence-angola',
  name: "Angola Independence Day",
  date: '11-11',
  countries: ['AO'],
  background: 'linear-gradient(135deg, #ff0000 0%, #000000 100%)',
  icon: '🇦🇴',
  description: "Happy Independence Day, Angola!",
},
{
  id: 'independence-malawi',
  name: "Malawi Independence Day",
  date: '07-06',
  countries: ['MW'],
  background: 'linear-gradient(135deg, #ce1126 0%, #000000 50%, #007849 100%)',
  icon: '🇲🇼',
  description: "Happy Independence Day, Malawi!",
},
{
  id: 'independence-lesotho',
  name: "Lesotho Independence Day",
  date: '10-04',
  countries: ['LS'],
  background: 'linear-gradient(135deg, #00209f 0%, #ffffff 50%, #009543 100%)',
  icon: '🇱🇸',
  description: "Happy Independence Day, Lesotho!",
},
{
  id: 'independence-swaziland',
  name: "Eswatini Independence Day",
  date: '09-06',
  countries: ['SZ'],
  background: 'linear-gradient(135deg, #3e5eb9 0%, #ffd900 50%, #d21034 100%)',
  icon: '🇸🇿',
  description: "Happy Independence Day, Eswatini!",
},

// --- NORTH AFRICA & MIDDLE EAST ---
{
  id: 'independence-egypt',
  name: "Egypt Revolution Day",
  date: '07-23',
  countries: ['EG'],
  background: 'linear-gradient(135deg, #ce1126 0%, #ffffff 50%, #000000 100%)',
  icon: '🇪🇬',
  description: "Happy Revolution Day, Egypt!",
},
{
  id: 'independence-morocco',
  name: "Morocco Independence Day",
  date: '11-18',
  countries: ['MA'],
  background: 'linear-gradient(135deg, #c1272d 0%, #006233 100%)',
  icon: '🇲🇦',
  description: "Happy Independence Day, Morocco!",
},
{
  id: 'independence-algeria',
  name: "Algeria Independence Day",
  date: '07-05',
  countries: ['DZ'],
  background: 'linear-gradient(135deg, #006233 0%, #ffffff 50%, #d21034 100%)',
  icon: '🇩🇿',
  description: "Happy Independence Day, Algeria!",
},
{
  id: 'independence-tunisia',
  name: "Tunisia Independence Day",
  date: '03-20',
  countries: ['TN'],
  background: 'linear-gradient(135deg, #e70013 0%, #ffffff 100%)',
  icon: '🇹🇳',
  description: "Happy Independence Day, Tunisia!",
},
{
  id: 'independence-libya',
  name: "Libya Independence Day",
  date: '12-24',
  countries: ['LY'],
  background: 'linear-gradient(135deg, #239e46 0%, #ffffff 33%, #e70013 66%, #000000 100%)',
  icon: '🇱🇾',
  description: "Happy Independence Day, Libya!",
},
{
  id: 'independence-uae',
  name: "UAE National Day",
  date: '12-02',
  countries: ['AE'],
  background: 'linear-gradient(135deg, #00732f 0%, #ffffff 33%, #ff0000 66%, #000000 100%)',
  icon: '🇦🇪',
  description: "Happy National Day, UAE!",
},
{
  id: 'independence-saudi',
  name: "Saudi National Day",
  date: '09-23',
  countries: ['SA'],
  background: 'linear-gradient(135deg, #006c35 0%, #ffffff 100%)',
  icon: '🇸🇦',
  description: "Happy National Day, Saudi Arabia!",
},
{
  id: 'independence-jordan',
  name: "Jordan Independence Day",
  date: '05-25',
  countries: ['JO'],
  background: 'linear-gradient(135deg, #007a3d 0%, #ffffff 33%, #ce1126 66%, #000000 100%)',
  icon: '🇯🇴',
  description: "Happy Independence Day, Jordan!",
},
{
  id: 'independence-lebanon',
  name: "Lebanon Independence Day",
  date: '11-22',
  countries: ['LB'],
  background: 'linear-gradient(135deg, #ed1c24 0%, #ffffff 50%, #ed1c24 100%)',
  icon: '🇱🇧',
  description: "Happy Independence Day, Lebanon!",
},

// --- CANADA & AUSTRALIA ---
{
  id: 'canada-day',
  name: "Canada Day",
  date: '07-01',
  countries: ['CA'],
  background: 'linear-gradient(135deg, #ff0000 0%, #ffffff 100%)',
  icon: '🇨🇦',
  description: "Happy Canada Day!",
},
{
  id: 'australia-day',
  name: "Australia Day",
  date: '01-26',
  countries: ['AU'],
  background: 'linear-gradient(135deg, #012169 0%, #ffffff 50%, #e4002b 100%)',
  icon: '🇦🇺',
  description: "Happy Australia Day!",
},

// --- EAST AFRICA ---
{
  id: 'independence-ethiopia',
  name: "Ethiopia Independence Day",
  date: '05-28',
  countries: ['ET'],
  background: 'linear-gradient(135deg, #ffc621 0%, #ef2b2d 50%, #078930 100%)',
  icon: '🇪🇹',
  description: "Happy Independence Day, Ethiopia!",
},
{
  id: 'independence-tanzania',
  name: "Tanzania Independence Day",
  date: '12-09',
  countries: ['TZ'],
  background: 'linear-gradient(135deg, #1eb53a 0%, #fcd116 50%, #00a3dd 100%)',
  icon: '🇹🇿',
  description: "Happy Independence Day, Tanzania!",
},
{
  id: 'independence-uganda',
  name: "Uganda Independence Day",
  date: '10-09',
  countries: ['UG'],
  background: 'linear-gradient(135deg, #fcdc04 0%, #000000 33%, #e4012e 66%, #fff 100%)',
  icon: '🇺🇬',
  description: "Happy Independence Day, Uganda!",
},
{
  id: 'independence-rwanda',
  name: "Rwanda Liberation Day",
  date: '07-04',
  countries: ['RW'],
  background: 'linear-gradient(135deg, #20603d 0%, #fad201 50%, #00a1de 100%)',
  icon: '🇷🇼',
  description: "Happy Liberation Day, Rwanda!",
},
{
  id: 'independence-burundi',
  name: "Burundi Independence Day",
  date: '07-01',
  countries: ['BI'],
  background: 'linear-gradient(135deg, #ce1126 0%, #ffffff 50%, #1eb53a 100%)',
  icon: '🇧🇮',
  description: "Happy Independence Day, Burundi!",
},
{
  id: 'independence-somalia',
  name: "Somalia Independence Day",
  date: '07-01',
  countries: ['SO'],
  background: 'linear-gradient(135deg, #4189dd 0%, #ffffff 100%)',
  icon: '🇸🇴',
  description: "Happy Independence Day, Somalia!",
},
{
  id: 'independence-djibouti',
  name: "Djibouti Independence Day",
  date: '06-27',
  countries: ['DJ'],
  background: 'linear-gradient(135deg, #6ab2e7 0%, #ffffff 33%, #12ad2b 66%, #d7141a 100%)',
  icon: '🇩🇯',
  description: "Happy Independence Day, Djibouti!",
},
{
  id: 'independence-eritrea',
  name: "Eritrea Independence Day",
  date: '05-24',
  countries: ['ER'],
  background: 'linear-gradient(135deg, #ef2b2d 0%, #fcd116 50%, #007a5e 100%)',
  icon: '🇪🇷',
  description: "Happy Independence Day, Eritrea!",
},
{
  id: 'independence-sudan',
  name: "Sudan Independence Day",
  date: '01-01',
  countries: ['SD'],
  background: 'linear-gradient(135deg, #d21034 0%, #ffffff 33%, #007229 66%, #000000 100%)',
  icon: '🇸🇩',
  description: "Happy Independence Day, Sudan!",
},
{
  id: 'independence-south-sudan',
  name: "South Sudan Independence Day",
  date: '07-09',
  countries: ['SS'],
  background: 'linear-gradient(135deg, #0f47af 0%, #ffffff 20%, #e31b23 40%, #007847 60%, #ffd100 80%, #000000 100%)',
  icon: '🇸🇸',
  description: "Happy Independence Day, South Sudan!",
},

  // ...continue adding for all countries and events as needed
  // --- NATIONAL & WORLD DAYS ---
  {
    id: 'workers-day',
    name: "International Workers' Day",
    date: '05-01',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🛠️',
    description: "Happy Workers' Day!",
  },
  {
    id: 'childrens-day-ng',
    name: "Children's Day (Nigeria)",
    date: '05-27',
    countries: ['NG'],
    background: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)',
    icon: '🧒',
    description: "Happy Children's Day, Nigeria!",
  },
  {
    id: 'youth-day-za',
    name: "Youth Day (South Africa)",
    date: '06-16',
    countries: ['ZA'],
    background: 'linear-gradient(135deg, #007749 0%, #ffb81c 50%, #de3831 100%)',
    icon: '🧑‍🎓',
    description: "Happy Youth Day, South Africa!",
  },
  {
    id: 'womens-day',
    name: "International Women's Day",
    date: '03-08',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f953c6 0%, #b91d73 100%)',
    icon: '♀️',
    description: "Celebrating women everywhere!",
  },
  {
    id: 'mothers-day',
    name: "Mother's Day",
    date: { rule: 'second Sunday in May' },
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🌷',
    description: "Celebrating mothers everywhere!",
  },
  {
    id: 'fathers-day',
    name: "Father's Day",
    date: { rule: 'third Sunday in June' },
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #232526 0%, #414345 100%)',
    icon: '👨‍👧‍👦',
    description: "Celebrating fathers everywhere!",
  },
  {
    id: 'aids-day',
    name: "World AIDS Day",
    date: '12-01',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #ff512f 0%, #dd2476 100%)',
    icon: '🎗️',
    description: "Support AIDS Awareness!",
  },
  {
    id: 'autism-awareness',
    name: "World Autism Awareness Day",
    date: '04-02',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #2980b9 0%, #6dd5fa 100%)',
    icon: '🧩',
    description: "Support Autism Awareness!",
  },
  {
    id: 'earth-day',
    name: "Earth Day",
    date: '04-22',
    countries: ['ALL'],
    background: 'linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)',
    icon: '🌍',
    description: "Protect our planet!",
  },
  {
    id: 'mandela-day',
    name: "Mandela Day",
    date: '07-18',
    countries: ['ZA'],
    background: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    icon: '🕊️',
    description: "Nelson Mandela International Day",
  },
  // 
  //   // ...
  // 294+ more entries for all major holidays, national days, world events, etc.
  // Each with a unique id, name, date/rule, countries, background, icon, and description
];
