// Example: List of banks for a few countries. Expand as needed.
export const banksByCountry: { [key: string]: { code: string; name: string }[] } = {
  US: [
    { code: 'JPMC', name: 'JPMorgan Chase' },
    { code: 'BAC', name: 'Bank of America' },
    { code: 'WFC', name: 'Wells Fargo' },
    { code: 'CITI', name: 'Citibank' },
    { code: 'GS', name: 'Goldman Sachs' },
    { code: 'MS', name: 'Morgan Stanley' },
    { code: 'USB', name: 'U.S. Bank' },
    { code: 'PNC', name: 'PNC Bank' },
    { code: 'TD', name: 'TD Bank' },
    { code: 'CAP1', name: 'Capital One' },
    { code: 'HSBC', name: 'HSBC Bank USA' },
    { code: 'BBT', name: 'BB&T' },
    { code: 'KEY', name: 'KeyBank' },
    { code: 'RF', name: 'Regions Bank' },
    { code: 'FITB', name: 'Fifth Third Bank' }
  ],
  KE: [
    { code: 'KCB', name: 'KCB Bank' },
    { code: 'EQUITY', name: 'Equity Bank' },
    { code: 'COOP', name: 'Co-operative Bank' },
    { code: 'STANBIC', name: 'Stanbic Bank' },
    { code: 'ABSA', name: 'Absa Bank' },
    { code: 'DIAMOND', name: 'Diamond Trust Bank' },
    { code: 'NCBA', name: 'NCBA Bank' },
    { code: 'STANCHART', name: 'Standard Chartered' },
    { code: 'BARCLAYS', name: 'Barclays Bank' },
    { code: 'HF', name: 'Housing Finance' }
  ],
  GH: [
    { code: 'GCB', name: 'GCB Bank' },
    { code: 'FIDELITY', name: 'Fidelity Bank' },
    { code: 'CAL', name: 'CAL Bank' },
    { code: 'ZENITH', name: 'Zenith Bank' },
    { code: 'STANBIC', name: 'Stanbic Bank' },
    { code: 'ECOBANK', name: 'Ecobank' },
    { code: 'UBA', name: 'UBA Bank' },
    { code: 'ACCESS', name: 'Access Bank' },
    { code: 'FBN', name: 'First Bank of Nigeria' },
    { code: 'GTB', name: 'Guaranty Trust Bank' }
  ],
  BW: [
    { code: 'FNB', name: 'First National Bank' },
    { code: 'STANBIC', name: 'Stanbic Bank' },
    { code: 'BARCLAYS', name: 'Barclays Bank' },
    { code: 'STANDARD', name: 'Standard Chartered' },
    { code: 'BANCABC', name: 'BancABC' },
    { code: 'BBS', name: 'Bank of Botswana' },
    { code: 'BBSL', name: 'Botswana Building Society' },
    { code: 'BBSL', name: 'Botswana Savings Bank' }
  ],
  EG: [
    { code: 'CIB', name: 'Commercial International Bank' },
    { code: 'QNB', name: 'QNB Alahli' },
    { code: 'AAIB', name: 'Arab African International Bank' },
    { code: 'HSBC', name: 'HSBC Bank Egypt' },
    { code: 'NBK', name: 'National Bank of Kuwait' },
    { code: 'ADIB', name: 'Abu Dhabi Islamic Bank' },
    { code: 'FAB', name: 'First Abu Dhabi Bank' },
    { code: 'ADCB', name: 'Abu Dhabi Commercial Bank' },
    { code: 'ENBD', name: 'Emirates NBD' },
    { code: 'MISR', name: 'Banque Misr' }
  ],
  IN: [
    { code: 'SBI', name: 'State Bank of India' },
    { code: 'HDFC', name: 'HDFC Bank' },
    { code: 'ICICI', name: 'ICICI Bank' },
    { code: 'PNB', name: 'Punjab National Bank' },
    { code: 'BOB', name: 'Bank of Baroda' },
    { code: 'CANARA', name: 'Canara Bank' },
    { code: 'AXIS', name: 'Axis Bank' },
    { code: 'UBI', name: 'Union Bank of India' },
    { code: 'IDBI', name: 'IDBI Bank' },
    { code: 'KOTAK', name: 'Kotak Mahindra Bank' }
  ],
  PK: [
    { code: 'HBL', name: 'HBL Bank' },
    { code: 'UBL', name: 'United Bank Limited' },
    { code: 'MCB', name: 'MCB Bank' },
    { code: 'ABL', name: 'Allied Bank' },
    { code: 'JS', name: 'JS Bank' },
    { code: 'BAHL', name: 'Bank Al Habib' },
    { code: 'SCB', name: 'Standard Chartered Bank' },
    { code: 'FBL', name: 'Faysal Bank' },
    { code: 'SBL', name: 'Summit Bank' },
    { code: 'BOP', name: 'Bank of Punjab' }
  ],
  CA: [
    { code: 'RBC', name: 'Royal Bank of Canada' },
    { code: 'TD', name: 'TD Bank' },
    { code: 'BMO', name: 'Bank of Montreal' },
    { code: 'SCOTIA', name: 'Scotiabank' },
    { code: 'CIBC', name: 'CIBC' },
    { code: 'NBC', name: 'National Bank of Canada' },
    { code: 'HSBC', name: 'HSBC Bank Canada' },
    { code: 'ATB', name: 'ATB Financial' },
    { code: 'VANCITY', name: 'Vancity' },
    { code: 'DESJARDINS', name: 'Desjardins' }
  ],
  GB: [
    { code: 'HSBC', name: 'HSBC' },
    { code: 'BARCLAYS', name: 'Barclays' },
    { code: 'LLOYDS', name: 'Lloyds Bank' },
    { code: 'RBS', name: 'Royal Bank of Scotland' },
    { code: 'SANTANDER', name: 'Santander UK' },
    { code: 'NATWEST', name: 'NatWest' },
    { code: 'TSB', name: 'TSB Bank' },
    { code: 'HALIFAX', name: 'Halifax' },
    { code: 'NATIONWIDE', name: 'Nationwide Building Society' },
    { code: 'COOP', name: 'The Co-operative Bank' }
  ],
  DE: [
    { code: 'DB', name: 'Deutsche Bank' },
    { code: 'COMMERZBANK', name: 'Commerzbank' },
    { code: 'KFW', name: 'KfW Bank' },
    { code: 'DZ', name: 'DZ Bank' },
    { code: 'LBBW', name: 'LBBW' },
    { code: 'BAYERLB', name: 'Bayerische Landesbank' },
    { code: 'NORDLB', name: 'Norddeutsche Landesbank' },
    { code: 'HELABA', name: 'Helaba' },
    { code: 'LBB', name: 'Landesbank Berlin' },
    { code: 'SPARKASSE', name: 'Sparkasse' }
  ],
  FR: [
    { code: 'BNP', name: 'BNP Paribas' },
    { code: 'CA', name: 'Crédit Agricole' },
    { code: 'SG', name: 'Société Générale' },
    { code: 'BPCE', name: 'BPCE Group' },
    { code: 'CMUT', name: 'Crédit Mutuel' },
    { code: 'LCL', name: 'LCL' },
    { code: 'HSBC', name: 'HSBC France' },
    { code: 'ING', name: 'ING Direct' },
    { code: 'HELLO', name: 'Hello Bank!' },
    { code: 'BRED', name: 'BRED Banque Populaire' }
  ],
  IT: [
    { code: 'UNICREDIT', name: 'UniCredit' },
    { code: 'INTESA', name: 'Intesa Sanpaolo' },
    { code: 'MPS', name: 'Monte dei Paschi di Siena' },
    { code: 'UBI', name: 'UBI Banca' },
    { code: 'BPER', name: 'BPER Banca' },
    { code: 'CARIGE', name: 'Carige' },
    { code: 'CREDEM', name: 'Credito Emiliano' },
    { code: 'BPM', name: 'Banco BPM' },
    { code: 'POPOLARE', name: 'Banca Popolare di Sondrio' },
    { code: 'CARIPARMA', name: 'Cariparma' }
  ],
  ES: [
    { code: 'SANTANDER', name: 'Banco Santander' },
    { code: 'BBVA', name: 'BBVA' },
    { code: 'CAIXA', name: 'CaixaBank' },
    { code: 'SABADELL', name: 'Banco Sabadell' },
    { code: 'BANKIA', name: 'Bankia' },
    { code: 'UNICAJA', name: 'Unicaja Banco' },
    { code: 'BANKINTER', name: 'Bankinter' },
    { code: 'KUTXABANK', name: 'Kutxabank' },
    { code: 'ABANCA', name: 'Abanca' },
    { code: 'IBERCAJA', name: 'Ibercaja' }
  ],
  AU: [
    { code: 'CBA', name: 'Commonwealth Bank' },
    { code: 'WBC', name: 'Westpac' },
    { code: 'NAB', name: 'National Australia Bank' },
    { code: 'ANZ', name: 'ANZ Bank' },
    { code: 'STG', name: 'St. George Bank' },
    { code: 'BENDIGO', name: 'Bendigo Bank' },
    { code: 'SUNCORP', name: 'Suncorp Bank' },
    { code: 'MACQUARIE', name: 'Macquarie Bank' },
    { code: 'ING', name: 'ING Bank Australia' },
    { code: 'BANKSA', name: 'BankSA' }
  ],
  SG: [
    { code: 'DBS', name: 'DBS Bank' },
    { code: 'OCBC', name: 'OCBC Bank' },
    { code: 'UOB', name: 'United Overseas Bank' },
    { code: 'CITIBANK', name: 'Citibank Singapore' },
    { code: 'HSBC', name: 'HSBC Singapore' },
    { code: 'SCB', name: 'Standard Chartered Bank' },
    { code: 'MAYBANK', name: 'Maybank Singapore' },
    { code: 'CIMB', name: 'CIMB Bank' },
    { code: 'RHB', name: 'RHB Bank' },
    { code: 'BOC', name: 'Bank of China' }
  ],
  CN: [
    { code: 'ICBC', name: 'Industrial and Commercial Bank of China' },
    { code: 'CCB', name: 'China Construction Bank' },
    { code: 'ABC', name: 'Agricultural Bank of China' },
    { code: 'BOC', name: 'Bank of China' },
    { code: 'BCOM', name: 'Bank of Communications' },
    { code: 'PSBC', name: 'Postal Savings Bank of China' },
    { code: 'CMB', name: 'China Merchants Bank' },
    { code: 'SPDB', name: 'Shanghai Pudong Development Bank' },
    { code: 'CIB', name: 'Industrial Bank' },
    { code: 'CMBC', name: 'China Minsheng Bank' }
  ],
  JP: [
    { code: 'MUFG', name: 'MUFG Bank' },
    { code: 'SMBC', name: 'Sumitomo Mitsui Banking Corporation' },
    { code: 'MIZUHO', name: 'Mizuho Bank' },
    { code: 'RESONA', name: 'Resona Bank' },
    { code: 'SBI', name: 'SBI Shinsei Bank' },
    { code: 'AOYAMA', name: 'Aozora Bank' },
    { code: 'NORTHERN', name: 'North Pacific Bank' },
    { code: 'CHIBA', name: 'Chiba Bank' },
    { code: 'HOKKAIDO', name: 'Hokkaido Bank' },
    { code: 'TOHOKU', name: 'Tohoku Bank' }
  ],
  KR: [
    { code: 'KB', name: 'KB Kookmin Bank' },
    { code: 'SHINHAN', name: 'Shinhan Bank' },
    { code: 'HANA', name: 'Hana Bank' },
    { code: 'WOORI', name: 'Woori Bank' },
    { code: 'NH', name: 'NH Bank' },
    { code: 'SC', name: 'Standard Chartered Korea' },
    { code: 'CITI', name: 'Citibank Korea' },
    { code: 'IBK', name: 'Industrial Bank of Korea' },
    { code: 'DGB', name: 'DGB Financial Group' },
    { code: 'BNK', name: 'BNK Financial Group' }
  ],
  BR: [
    { code: 'ITAU', name: 'Itaú Unibanco' },
    { code: 'BRADESCO', name: 'Bradesco' },
    { code: 'SANTANDER', name: 'Santander Brasil' },
    { code: 'BB', name: 'Banco do Brasil' },
    { code: 'CAIXA', name: 'Caixa Econômica Federal' },
    { code: 'NUBANK', name: 'Nubank' },
    { code: 'INTER', name: 'Banco Inter' },
    { code: 'BTG', name: 'BTG Pactual' },
    { code: 'SAFRA', name: 'Banco Safra' },
    { code: 'VOTORANTIM', name: 'Banco Votorantim' }
  ],
  MX: [
    { code: 'BBVA', name: 'BBVA México' },
    { code: 'SANTANDER', name: 'Santander México' },
    { code: 'BANAMEX', name: 'Banamex' },
    { code: 'BANORTE', name: 'Banorte' },
    { code: 'HSBC', name: 'HSBC México' },
    { code: 'SCOTIABANK', name: 'Scotiabank México' },
    { code: 'INBURSA', name: 'Banco Inbursa' },
    { code: 'BANREGIO', name: 'Banregio' },
    { code: 'BANBAJIO', name: 'Banco del Bajío' },
    { code: 'BANCOPPEL', name: 'Bancoppel' }
  ],
  RU: [
    { name: 'Sberbank', code: '045' },
    { name: 'VTB Bank', code: '100' },
    { name: 'Gazprombank', code: '049' },
    { name: 'Alfa-Bank', code: '044' },
    { name: 'Russian Agricultural Bank', code: '046' },
    { name: 'Bank Otkritie', code: '048' },
    { name: 'Promsvyazbank', code: '047' },
    { name: 'Rosbank', code: '049' },
    { name: 'Moscow Credit Bank', code: '050' },
    { name: 'Sovcombank', code: '051' }
  ],
  TR: [
    { name: 'Ziraat Bankası', code: '10' },
    { name: 'İşbank', code: '64' },
    { name: 'Garanti BBVA', code: '62' },
    { name: 'Akbank', code: '46' },
    { name: 'Yapı Kredi', code: '67' },
    { name: 'Halkbank', code: '12' },
    { name: 'VakifBank', code: '15' },
    { name: 'QNB Finansbank', code: '111' },
    { name: 'DenizBank', code: '134' },
    { name: 'TEB', code: '32' }
  ],
  SA: [
    { name: 'National Commercial Bank', code: 'NCB' },
    { name: 'Al Rajhi Bank', code: 'RJHI' },
    { name: 'Samba Financial Group', code: 'SAMBA' },
    { name: 'Riyad Bank', code: 'RYAD' },
    { name: 'Banque Saudi Fransi', code: 'BSFR' },
    { name: 'Arab National Bank', code: 'ANB' },
    { name: 'The Saudi British Bank', code: 'SABB' },
    { name: 'Alinma Bank', code: 'INMA' },
    { name: 'Bank Aljazira', code: 'BJAZ' },
    { name: 'Gulf International Bank', code: 'GIB' }
  ],
  AE: [
    { name: 'First Abu Dhabi Bank', code: 'FAB' },
    { name: 'Emirates NBD', code: 'EBILAEAD' },
    { name: 'Abu Dhabi Commercial Bank', code: 'ADCBAEAA' },
    { name: 'Dubai Islamic Bank', code: 'DUIBAEAD' },
    { name: 'Mashreq Bank', code: 'BOMLAEAD' },
    { name: 'RAKBANK', code: 'NRAKAEAD' },
    { name: 'Abu Dhabi Islamic Bank', code: 'ABDIAEAD' },
    { name: 'Commercial Bank of Dubai', code: 'CBDUAEAD' },
    { name: 'Union National Bank', code: 'UNBEAEAD' },
    { name: 'Sharjah Islamic Bank', code: 'NBSHAEAS' }
  ],
  NG: [
    { code: 'ZENITH', name: 'Zenith Bank' },
    { code: 'UBA', name: 'United Bank for Africa' },
    { code: 'FBN', name: 'First Bank of Nigeria' },
    { code: 'GTB', name: 'Guaranty Trust Bank' },
    { code: 'ACCESS', name: 'Access Bank' },
    { code: 'FCMB', name: 'First City Monument Bank' },
    { code: 'UNION', name: 'Union Bank of Nigeria' },
    { code: 'STANBIC', name: 'Stanbic IBTC Bank' },
    { code: 'FIDELITY', name: 'Fidelity Bank' },
    { code: 'WEMA', name: 'Wema Bank' }
  ],
  ZA: [
    { code: 'FNB', name: 'First National Bank' },
    { code: 'ABSA', name: 'Absa Bank' },
    { code: 'STANBIC', name: 'Standard Bank' },
    { code: 'NEDBANK', name: 'Nedbank' },
    { code: 'CAPITEC', name: 'Capitec Bank' },
    { code: 'AFRICAN', name: 'African Bank' },
    { code: 'BIDVEST', name: 'Bidvest Bank' },
    { code: 'GRINDROD', name: 'Grindrod Bank' },
    { code: 'SASFIN', name: 'Sasfin Bank' },
    { code: 'TMRW', name: 'TymeBank' },
    { code: 'DISCOVERY', name: 'Discovery Bank' },
    { code: 'INVESTEC', name: 'Investec Bank' },
    { code: 'MERCANTILE', name: 'Mercantile Bank' },
    { code: 'SAHL', name: 'South African Home Loans' },
    { code: 'UBA', name: 'United Bank for Africa' }
  ],
  // ...add more countries and banks as needed
};
